USE [master]
GO

/****** Objet : Database [TemperatureBD] Date de script : 2026-08-01 12:44:23 ******/
DROP DATABASE [TemperatureBD]
GO

/****** Objet : Database [TemperatureBD] Date de script : 2026-08-01 12:44:23 ******/
CREATE DATABASE [TemperatureBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TemperatureBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TemperatureBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TemperatureBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TemperatureBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TemperatureBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TemperatureBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TemperatureBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TemperatureBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TemperatureBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TemperatureBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [TemperatureBD] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TemperatureBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TemperatureBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TemperatureBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TemperatureBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TemperatureBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TemperatureBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TemperatureBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TemperatureBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TemperatureBD] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TemperatureBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TemperatureBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TemperatureBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TemperatureBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TemperatureBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TemperatureBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TemperatureBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TemperatureBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TemperatureBD] SET  MULTI_USER 
GO

ALTER DATABASE [TemperatureBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TemperatureBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TemperatureBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TemperatureBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TemperatureBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TemperatureBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TemperatureBD] SET QUERY_STORE = ON
GO

ALTER DATABASE [TemperatureBD] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TemperatureBD] SET  READ_WRITE 
GO


